### ISSUE TITLE
Dependency missing running container

### ISSUE THREAD

**Issue by ijhoskins** [ribosomeprofiling/ribograph#15]
Running Docker 4.27.0 on Mac 2.4 GHz Quad-Core Intel Core i5 with Ventura 13.4.1

pify dependency is not found when running the container:

```
docker compose -f docker-compose_local.yml up
[+] Running 2/2
 ✔ Network docker_default        Created                                                                                                                                   0.1s 
 ✔ Container docker-ribograph-1  Created                                                                                                                                   0.1s 
Attaching to ribograph-1
ribograph-1  | No changes detected
ribograph-1  | Operations to perform:
ribograph-1  |   Apply all migrations: admin, auth, browser, contenttypes, sessions
ribograph-1  | Running migrations:
ribograph-1  |   No migrations to apply.
ribograph-1  | npm WARN deprecated mumath@3.3.4: Redundant dependency in your project.
ribograph-1  | 
ribograph-1  | changed 538 packages, and audited 554 packages in 28s
ribograph-1  | 
ribograph-1  | 51 packages are looking for funding
ribograph-1  |   run `npm fund` for details
ribograph-1  | 
ribograph-1  | 9 vulnerabilities (5 moderate, 3 high, 1 critical)
ribograph-1  | 
ribograph-1  | To address issues that do not require attention, run:
ribograph-1  |   npm audit fix
ribograph-1  | 
ribograph-1  | To address all issues (including breaking changes), run:
ribograph-1  |   npm audit fix --force
ribograph-1  | 
ribograph-1  | Run `npm audit` for details.
ribograph-1  | 
ribograph-1  | > ribobase-graphs@0.0.0 build
ribograph-1  | > run-p type-check build-only
ribograph-1  | 
ribograph-1  | node:internal/modules/cjs/loader:1137
ribograph-1  |   throw err;
ribograph-1  |   ^
ribograph-1  | 
ribograph-1  | Error: Cannot find module 'pify'
ribograph-1  | Require stack:
ribograph-1  | - /home/ribograph/web/node_modules/load-json-file/index.js
ribograph-1  | - /home/ribograph/web/node_modules/read-pkg/index.js
ribograph-1  | - /home/ribograph/web/node_modules/npm-run-all/lib/read-package-json.js
ribograph-1  | - /home/ribograph/web/node_modules/npm-run-all/lib/index.js
ribograph-1  | - /home/ribograph/web/node_modules/npm-run-all/bin/run-p/main.js
ribograph-1  | - /home/ribograph/web/node_modules/npm-run-all/bin/common/bootstrap.js
ribograph-1  | - /home/ribograph/web/node_modules/npm-run-all/bin/run-p/index.js
ribograph-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
ribograph-1  |     at Module._load (node:internal/modules/cjs/loader:975:27)
ribograph-1  |     at Module.require (node:internal/modules/cjs/loader:1225:19)
ribograph-1  |     at require (node:internal/modules/helpers:177:18)
ribograph-1  |     at Object.<anonymous> (/home/ribograph/web/node_modules/load-json-file/index.js:6:14)
ribograph-1  |     at Module._compile (node:internal/modules/cjs/loader:1356:14)
ribograph-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
ribograph-1  |     at Module.load (node:internal/modules/cjs/loader:1197:32)
ribograph-1  |     at Module._load (node:internal/modules/cjs/loader:1013:12)
ribograph-1  |     at Module.require (node:internal/modules/cjs/loader:1225:19) {
ribograph-1  |   code: 'MODULE_NOT_FOUND',
ribograph-1  |   requireStack: [
ribograph-1  |     '/home/ribograph/web/node_modules/load-json-file/index.js',
ribograph-1  |     '/home/ribograph/web/node_modules/read-pkg/index.js',
ribograph-1  |     '/home/ribograph/web/node_modules/npm-run-all/lib/read-package-json.js',
ribograph-1  |     '/home/ribograph/web/node_modules/npm-run-all/lib/index.js',
ribograph-1  |     '/home/ribograph/web/node_modules/npm-run-all/bin/run-p/main.js',
ribograph-1  |     '/home/ribograph/web/node_modules/npm-run-all/bin/common/bootstrap.js',
ribograph-1  |     '/home/ribograph/web/node_modules/npm-run-all/bin/run-p/index.js'
ribograph-1  |   ]
ribograph-1  | }
ribograph-1  | 
ribograph-1  | Node.js v18.19.0
ribograph-1  | Watching for file changes with StatReloader
ribograph-1  | Performing system checks...
ribograph-1  | 
ribograph-1  | System check identified no issues (0 silenced).
ribograph-1  | January 29, 2024 - 21:25:21
ribograph-1  | Django version 3.2.15, using settings 'ribograph.settings'
ribograph-1  | Starting development server at http://0.0.0.0:8000/
ribograph-1  | Quit the server with CONTROL-C.
ribograph-1  | [29/Jan/2024 21:25:38] "GET / HTTP/1.1" 302 0
ribograph-1  | [29/Jan/2024 21:25:38] "GET /add_admin_user HTTP/1.1" 200 4288
ribograph-1  | [29/Jan/2024 21:25:39] "GET /static/browser/style.css HTTP/1.1" 200 1927
ribograph-1  | Not Found: /favicon.ico
ribograph-1  | [29/Jan/2024 21:25:40] "GET /favicon.ico HTTP/1.1" 404 8930
```

**Comment by ijhoskins** [comment]
I was able to get pass the pify error by installing nvm, then installing node and npm, then installing pify.

Now I see a new error in /home/ribograph/web/node_modules/supports-color/index.js

```
docker compose -f docker-compose_local.yml up
[+] Running 1/0
 ✔ Container dockernosync-ribograph-1  Created                                                                                                                         0.0s 
Attaching to ribograph-1
ribograph-1  | No changes detected
ribograph-1  | Operations to perform:
ribograph-1  |   Apply all migrations: admin, auth, browser, contenttypes, sessions
ribograph-1  | Running migrations:
ribograph-1  |   No migrations to apply.
ribograph-1  | 
ribograph-1  | added 1 package, and audited 558 packages in 2s
ribograph-1  | 
ribograph-1  | 53 packages are looking for funding
ribograph-1  |   run `npm fund` for details
ribograph-1  | 
ribograph-1  | 4 vulnerabilities (1 moderate, 2 high, 1 critical)
ribograph-1  | 
ribograph-1  | To address all issues (including breaking changes), run:
ribograph-1  |   npm audit fix --force
ribograph-1  | 
ribograph-1  | Run `npm audit` for details.
ribograph-1  | 
ribograph-1  | > ribobase-graphs@0.0.0 build
ribograph-1  | > run-p type-check build-only
ribograph-1  | 
ribograph-1  | /home/ribograph/web/node_modules/supports-color/index.js:8
ribograph-1  | if (hasFlag('no-color') ||
ribograph-1  |     ^
ribograph-1  | 
ribograph-1  | TypeError: hasFlag is not a function
ribograph-1  |     at Object.<anonymous> (/home/ribograph/web/node_modules/supports-color/index.js:8:5)
ribograph-1  |     at Module._compile (node:internal/modules/cjs/loader:1356:14)
ribograph-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
ribograph-1  |     at Module.load (node:internal/modules/cjs/loader:1197:32)
ribograph-1  |     at Module._load (node:internal/modules/cjs/loader:1013:12)
ribograph-1  |     at Module.require (node:internal/modules/cjs/loader:1225:19)
ribograph-1  |     at require (node:internal/modules/helpers:177:18)
ribograph-1  |     at Object.<anonymous> (/home/ribograph/web/node_modules/chalk/index.js:4:21)
ribograph-1  |     at Module._compile (node:internal/modules/cjs/loader:1356:14)
ribograph-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
ribograph-1  | 
ribograph-1  | Node.js v18.19.0
ribograph-1  | Watching for file changes with StatReloader
ribograph-1  | Performing system checks...
ribograph-1  | 
ribograph-1  | System check identified no issues (0 silenced).
ribograph-1  | February 01, 2024 - 18:38:40
ribograph-1  | Django version 3.2.15, using settings 'ribograph.settings'
ribograph-1  | Starting development server at http://0.0.0.0:8000/
ribograph-1  | Quit the server with CONTROL-C.
```

**Comment by ijhoskins** [comment]
I recloned the repository, rebuilt, and things look fine now.
